[build]
  NETLIFY_USE_YARN = true
  command = "npm install && npm run build"
  functions = "dist"

[functions.node-fetch]
  external_node_modules = ["node-fetch"]

[[redirects]]
  from = '/*'
  to = '/.netlify/functions/:splat'
  status = 200

[dev]
  publish = "dist"