[dev]
  autoLaunch = false

[build]
  publish = "netlify/site/"

[[edge_functions]]
  path = "/classic"
  function = "classic"

[[edge_functions]]
  path = "/classic/*"
  function = "classic"

[[edge_functions]]
  path = "/inspirobot"
  function = "inspirobot"

[[edge_functions]]
  path = "/kaamelott"
  function = "kaamelott"